name: Deploy via SSH
run-name: Deploy via SSH triggered by ${{ github.actor }} on ${{ github.ref }}

on:
  push:
    branches:
      - main
concurrency:
  group: deploy-to-production
  cancel-in-progress: true
jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          passphrase: ${{ secrets.DO_PASSPHRASE }}
          script: |
            set -e
            set -x 
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            nvm install --lts
            nvm use --lts

            echo "checking node version..."
            node --version
            npm --version
            
            echo "Testing SSH connection to remote server..."
            hostname
            whoami
            cd ~/CVPilot
            git fetch --prune origin
            git checkout --force main
            git reset --hard origin/main
            git clean -fd
            echo "Deploying backend..."
            # ===== Backend =====
            cd backend
            npm ci
            npx prisma generate
            npx prisma migrate deploy
            npm run build
            if ! command -v pm2 > /dev/null; then
              npm install -g pm2
            fi
            pm2 reload cvpilot-backend ||  pm2 start npm --name cvpilot-backend -- start
            pm2 status
            cd ..
            echo "Deploying frontend..."
            # ===== Frontend =====
            cd frontend
            npm ci
            npm run build
            sudo mkdir -p /var/www/CVPilot/
            sudo rsync -a --delete dist/ /var/www/CVPilot/
            echo "Deployment complete!"