name: Deploy via SSH
run-name: Deploy via SSH triggered by ${{ github.actor }} on ${{ github.ref }}

on:
  push:
    branches:
      - main
concurrency:
  group: deploy-to-production
  cancel-in-progress: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
        CLERK_PUBLISHABLE_KEY: ${{ secrets.CLERK_PUBLISHABLE_KEY }}
        CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
        VITE_CLERK_PUBLISHABLE_KEY: ${{ secrets.VITE_CLERK_PUBLISHABLE_KEY }}
        CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
        CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
        CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}
        ADZUNA_APP_ID: ${{secrets.ADZUNA_APP_ID}}
        ADZUNA_APP_KEY: ${{secrets.ADZUNA_APP_KEY}}
    steps:
      - name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          passphrase: ${{ secrets.DO_PASSPHRASE }}
          envs: DATABASE_URL,FRONTEND_URL,CLERK_SECRET_KEY,VITE_CLERK_PUBLISHABLE_KEY,CLERK_PUBLISHABLE_KEY,CLOUDINARY_CLOUD_NAME,CLOUDINARY_API_KEY,CLOUDINARY_API_SECRET,GEMINI_API_KEY,VITE_BACKEND_URL,ADZUNA_APP_ID,ADZUNA_APP_KEY
          script: |
            set -e
            set -x 
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            nvm use --lts || (nvm install --lts && nvm use --lts)

            echo "checking node version..."
            node --version
            npm --version
            
            echo "Testing SSH connection to remote server..."
            hostname
            whoami
            cd ~/CVPilot
            git fetch --prune origin
            git checkout --force main
            git reset --hard origin/main
            git clean -fd
            echo "Deploying backend..."
            # ===== Backend =====
            cd backend
            echo "🔧 Generating .env file..."
            set +x
            tmp_file=".env.tmp"
            > "$tmp_file"
            if [ ! -f ".env.sample" ]; then
              echo "Error: .env.sample file not found!"
              exit 1
            fi
            while IFS= read -r line || [ -n "$line" ]; do
              if [[ -z "$line" || "$line" == \#* ]]; then
                continue
              fi
            key=$(echo "$line" | cut -d '=' -f 1 | xargs)
            echo "Processing $key"
            value=$(printenv "$key")
            if ! printenv "$key" > /dev/null; then
              echo "❌ Missing env: $key"
              exit 1
            fi
            printf "%s=%s\n" "$key" "$value" >> "$tmp_file"
            done < .env.sample 
            mv "$tmp_file" .env
            chmod 600 .env
            echo "✅ .env file generated successfully"
            npm ci
            npx prisma generate
            npx prisma migrate deploy
            npm run build
            if ! command -v pm2 > /dev/null; then
              npm install -g pm2
            fi
            pm2 reload cvpilot-backend ||  pm2 start npm --name cvpilot-backend -- start
            pm2 status
            for i in {1..10}; do
              if curl -f http://localhost:3000/health; then
                echo "✅ Server is up"
                break
              fi
              echo "⏳ Waiting for server..."
              sleep 2
            done
            curl -f http://localhost:3000/health || exit 1
            cd ..
            echo "Deploying frontend..."
            # ===== Frontend =====
            cd frontend
            echo "🔧 Generating .env file..."
            set +x
            tmp_file=".env.tmp"
            > "$tmp_file"
            if [ ! -f ".env.sample" ]; then
              echo "Error: .env.sample file not found!"
              exit 1
            fi
            while IFS= read -r line || [ -n "$line" ]; do
              if [[ -z "$line" || "$line" == \#* ]]; then
                continue
              fi
            key=$(echo "$line" | cut -d '=' -f 1 | xargs)
            echo "Processing $key"
            value=$(printenv "$key")
            if ! printenv "$key" > /dev/null; then
              echo "❌ Missing env: $key"
              exit 1
            fi
            printf "%s=%s\n" "$key" "$value" >> "$tmp_file"
            done < .env.sample 
            mv "$tmp_file" .env
            chmod 600 .env
            echo "✅ .env file generated successfully"
            npm install --package-lock-only
            npm ci
            npm run build
            sudo mkdir -p /var/www/CVPilot/
            sudo rsync -a --delete dist/ /var/www/CVPilot/
            echo "Deployment complete!"