name: Test SSH

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          passphrase: ${{ secrets.DO_PASSPHRASE }}
          script: |
            whoami
            pwd